In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix

from matplotlib.colors import ListedColormap

In [64]:
dataset = pd.read_csv('./../XAUUSD_2010-2023.csv')


In [128]:

dataset=dataset.head(700)
# dataset.head(200_000)

In [129]:
# mengambil nilai High dan low 
x = dataset.iloc[:, [2, 3]].values
# mengambil nilai open
y = dataset.iloc[:, 1].values

In [153]:
x

array([[1100.  , 1098.05],
       [1100.3 , 1099.45],
       [1100.1 , 1099.3 ],
       ...,
       [1124.48, 1123.78],
       [1124.83, 1124.1 ],
       [1124.25, 1123.65]])

In [154]:
y

array([1098.45, 1100.  , 1099.7 , 1099.5 , 1099.4 , 1098.95, 1098.85,
       1098.55, 1097.2 , 1097.65, 1097.7 , 1096.85, 1095.73, 1094.63,
       1094.43, 1093.48, 1094.63, 1095.28, 1095.38, 1095.08, 1094.98,
       1095.65, 1096.03, 1094.6 , 1094.58, 1095.15, 1095.33, 1095.38,
       1094.78, 1095.1 , 1095.1 , 1094.93, 1094.73, 1094.9 , 1095.23,
       1095.35, 1095.35, 1096.1 , 1096.18, 1098.13, 1098.  , 1098.28,
       1097.55, 1098.63, 1098.83, 1098.38, 1097.83, 1097.5 , 1098.03,
       1098.08, 1098.38, 1098.38, 1098.73, 1097.63, 1097.53, 1098.08,
       1097.98, 1097.68, 1097.98, 1098.48, 1098.78, 1099.28, 1100.68,
       1100.13, 1099.88, 1099.73, 1100.38, 1100.48, 1101.68, 1101.73,
       1101.88, 1101.53, 1101.78, 1101.78, 1102.08, 1101.78, 1101.78,
       1101.83, 1102.73, 1102.05, 1102.35, 1102.5 , 1103.4 , 1102.73,
       1102.58, 1102.95, 1103.28, 1103.55, 1102.75, 1102.05, 1101.73,
       1102.95, 1103.13, 1102.98, 1102.18, 1102.53, 1102.58, 1101.95,
       1102.53, 1101

In [132]:
x_train, x_test, y_train, y_test = train_test_split(
    x,  # memasukan data x low dan high
    y,  # memasukan data y open
    test_size=0.25,  # adalah berapa persen data yang akan di test
    random_state=0
)

In [133]:
print(x_train)

[[1115.1  1114.75]
 [1118.68 1118.48]
 [1095.43 1095.2 ]
 ...
 [1124.65 1123.98]
 [1117.98 1117.93]
 [1125.05 1124.68]]


In [134]:
len(x_train)

525

In [135]:
len(x)

700

In [136]:
len(x_test)

175

In [137]:
len(y)

700

In [138]:
len(y_test)

175

In [139]:
len(y_train)

525

In [140]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [150]:
print(x_train)
print('------------')

[[-0.3285853  -0.262127  ]
 [ 0.08850138  0.1724066 ]
 [-2.62023196 -2.53964227]
 ...
 [ 0.7840342   0.8131398 ]
 [ 0.00694812  0.10833328]
 [ 0.83063606  0.89468766]]
------------


In [151]:
print(x_test)
print('------------')

[[ 3.50636862e-01  4.25204973e-01]
 [ 4.26364891e-01  4.75298659e-01]
 [-2.24741705e+00 -2.21345083e+00]
 [ 5.83646182e-01  5.56846520e-01]
 [-2.73673662e+00 -2.77496610e+00]
 [ 1.66559500e-01  2.32985014e-01]
 [ 2.69083601e-01  3.49481958e-01]
 [-2.67032897e+00 -2.61536529e+00]
 [-6.29546799e-02 -1.16585704e-02]
 [-1.93867970e+00 -1.91055877e+00]
 [ 7.08306168e-01  6.98972793e-01]
 [ 3.85588260e-01  4.81123506e-01]
 [ 1.35103242e-01  1.10663222e-01]
 [ 4.32190124e-01  4.69473812e-01]
 [-1.68819468e+00 -1.63912089e+00]
 [ 6.38403372e-01  6.69848557e-01]
 [ 6.26752906e-01  5.76651001e-01]
 [ 5.37044318e-01  6.03445298e-01]
 [ 6.94811600e-03 -2.33881485e-03]
 [ 5.77820949e-01  5.53351612e-01]
 [ 2.36462296e-01  2.73758944e-01]
 [ 6.03451974e-01  6.67518618e-01]
 [ 6.96655702e-01  7.39746723e-01]
 [ 6.59374211e-01  7.10622487e-01]
 [-4.70234998e-03  2.67854213e-02]
 [ 1.43258568e-01  2.09685625e-01]
 [-1.63528160e-02 -4.31127455e-02]
 [ 1.51034422e-02 -5.83372320e-03]
 [ 6.26752906e-01  6

In [152]:
classifier = KNeighborsClassifier(
    n_neighbors=5,
    metric='euclidean',
    p=2,
    
    
)

In [147]:
classifier.fit(x_train, y_train)

ValueError: Unknown label type: continuous. Maybe you are trying to fit a classifier, which expects discrete classes on a regression target with continuous values.

In [148]:
KNeighborsClassifier(algorithm='auto',
                     leaf_size=30,
                     metric='minkowski',
                     metric_params=None,
                     n_jobs=None,
                     n_neighbors=5,
                     p=2,
                     weights='uniform')

KNeighborsClassifier()

In [149]:
y_pred = classifier.predict(x_test)
y_pred

NotFittedError: This KNeighborsClassifier instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [121]:
cm = confusion_matrix(y_test, y_pred)
cm

NameError: name 'y_pred' is not defined

In [122]:
x_set, y_set = x_train, y_train
x1, x2 = np.meshgrid(
    np.arange(
        start=x_set[:, 0].min() - 1,
        stop=x_set[:, 0].max() + 1,
        step=0.01
    ),
    np.arange(
        start=x_set[:, 1].min() - 1,
        stop=x_set[:, 1].max() + 1,
        step=0.01
    ),
)
plt.contourf(x1, x2, classifier
             .predict(
    np.array([x1.ravel(), x2.ravel()]).T
)
             .reshape(x1.shape),
             alpha=0.75,
             cmap=ListedColormap(('red', 'green'))
             )

plt.xlim(x1.min(), x1.max())
plt.ylim(x2.min(), x2.max())

for i, j in enumerate(np.unique(y_set)):
    plt.scatter(x_set[y_set == j, 0],
                x_set[y_set == j, 1],
                c=ListedColormap(('red', 'green'))(i),
                label=j)

plt.title('Klasifikasi Data dengan K-NN (Data Training)')
plt.xlabel('Umur')
plt.ylabel('Estimasi Gaji')
plt.legend()
plt.show()

NotFittedError: This KNeighborsClassifier instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [123]:
x_set, y_set = x_test, y_test
x1, x2 = np.meshgrid(
    np.arange(
        start=x_set[:, 0].min() - 1,
        stop=x_set[:, 0].max() + 1,
        step=0.01
    ),
    np.arange(
        start=x_set[:, 1].min() - 1,
        stop=x_set[:, 1].max() + 1,
        step=0.01
    ),
)
plt.contourf(x1, x2, classifier
             .predict(
    np.array([x1.ravel(), x2.ravel()]).T
)
             .reshape(x1.shape),
             alpha=0.75,
             cmap=ListedColormap(('red', 'green'))
             )

plt.xlim(x1.min(), x1.max())
plt.ylim(x2.min(), x2.max())

for i, j in enumerate(np.unique(y_set)):
    plt.scatter(x_set[y_set == j, 0],
                x_set[y_set == j, 1],
                c=ListedColormap(('red', 'green'))(i),
                label=j)

plt.title('Klasifikasi Data dengan K-NN (Data Testing)')
plt.xlabel('Umur')
plt.ylabel('Estimasi Gaji')
plt.legend()
plt.show()

NotFittedError: This KNeighborsClassifier instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.