In [5]:
import numpy as np

# Operasi di Numpy
coba = np.arange(0, 11)


In [6]:
coba

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
coba+5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [8]:
coba+coba

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [11]:
coba_list=[0,1,2,3,4,5,6,7,8,9,10]
coba_list+coba_list# malah menambah jumlah list


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [12]:
coba*2 # isi nya di kali 2 semua

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [13]:
coba_list*3# malah di lipatkan  jumlah angka nya

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10]

In [14]:
coba

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
coba-coba

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
coba-100 

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [18]:
coba/coba# error tapi masih di jalankan

C:\Users\liar88828\AppData\Local\Temp\ipykernel_6708\1510214551.py:1: RuntimeWarning: invalid value encountered in divide
  coba/coba


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [21]:
1/coba#error tapi masih di jalanakan

C:\Users\liar88828\AppData\Local\Temp\ipykernel_6708\3029460184.py:1: RuntimeWarning: divide by zero encountered in divide
  1/coba#error tapi masih di jalanakan


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [24]:
np.sqrt(coba)# di trik akar semua angka

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [25]:
np.exp(coba)#  

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [27]:
coba.max()


10

In [28]:
coba.min()

0

In [29]:
np.min(coba)

0

In [30]:
np.sin(coba)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [31]:
np.log(coba)

C:\Users\liar88828\AppData\Local\Temp\ipykernel_6708\110349656.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(coba)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])