In [ ]:
import numpy as np

angka = [1, 2, 3]


In [0]:
angkanp = np.array(angka)

In [0]:
angkanp

In [31]:
angka * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [32]:
versilist = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [33]:
versinumpy = np.array(versilist)
print(versilist)


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [34]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.arange(0, 20, 3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [21]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
np.zeros((2, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
np.linspace(0, 8, 10)

array([0.        , 0.88888889, 1.77777778, 2.66666667, 3.55555556,
       4.44444444, 5.33333333, 6.22222222, 7.11111111, 8.        ])

In [ ]:
# identity matrix

In [36]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])