In [2]:
import numpy as np

In [3]:
# bilangan distribusi uniform
np.random.rand(7)

array([0.45580037, 0.14545287, 0.62121475, 0.19749329, 0.54959964,
       0.92100676, 0.77776041])

In [6]:
# bilangan distribusi uniform matrix 2 dimension
np.random.rand(5, 4)

array([[0.54767742, 0.49499931, 0.90519369, 0.61288298],
       [0.68071633, 0.67941615, 0.09018076, 0.99453115],
       [0.24425902, 0.75617972, 0.98365748, 0.66262216],
       [0.08168018, 0.50843017, 0.45565141, 0.75835441],
       [0.39716794, 0.50109481, 0.10334936, 0.43037194]])

In [7]:
# bilangan distribusi normal (gaussian)
np.random.randn(10)

array([-0.75071679, -0.73932418,  1.11628859, -1.68803929,  0.11583771,
        0.62678268,  1.04227421, -0.10019891,  0.53047107,  1.83368134])

In [13]:
# bilangan distribusi normal (gaussian) matrik 2 dimension
from numpy.random import randn, randint

randn(6, 2)

array([[-1.00702622, -0.4560861 ],
       [-2.04015265, -1.14654495],
       [ 1.21253244, -0.18962812],
       [ 1.41948853,  0.04059198],
       [-2.34001071, -0.71862867],
       [ 0.09731888, -1.37424706]])

In [17]:
randint(0, 10)

0

In [19]:
randint(0, 10, 5)

array([8, 2, 8, 0, 6])

In [21]:
bilangan = randint(0, 100, 20)
bilangan

array([74, 75, 46, 61, 51, 95, 37, 54, 32, 46, 22, 88, 39, 21, 66, 69, 68,
        9, 70, 39])

In [30]:
bilangan.reshape(2, 10)

array([[74, 75, 46, 61, 51, 95, 37, 54, 32, 46],
       [22, 88, 39, 21, 66, 69, 68,  9, 70, 39]])

In [38]:
coba = randint(0, 10, 20).reshape(4, 5)
coba

array([[2, 3, 9, 0, 8],
       [1, 9, 1, 8, 3],
       [7, 4, 1, 7, 7],
       [6, 1, 3, 8, 8]])

In [50]:
newcoba = coba.reshape(2, 10)
coba

array([[2, 3, 9, 0, 8],
       [1, 9, 1, 8, 3],
       [7, 4, 1, 7, 7],
       [6, 1, 3, 8, 8]])

In [51]:
newcoba

array([[2, 3, 9, 0, 8, 1, 9, 1, 8, 3],
       [7, 4, 1, 7, 7, 6, 1, 3, 8, 8]])

In [54]:
coba = newcoba
coba

array([[2, 3, 9, 0, 8, 1, 9, 1, 8, 3],
       [7, 4, 1, 7, 7, 6, 1, 3, 8, 8]])

In [58]:
coba1d = randint(0, 100, 20)
coba2d = randint(0, 100, 20).reshape(4, 5)

In [60]:
coba1d

array([46, 87, 75, 79, 23, 24, 85, 24, 70, 22, 50, 29, 29, 39, 58,  3, 60,
       20, 51, 54])

In [62]:
coba2d

array([[28,  1, 28, 98, 98],
       [17, 68, 84, 36, 31],
       [41, 49, 21, 17, 32],
       [97, 25, 25, 35, 16]])

In [63]:
coba1d.max()

87

In [64]:
coba2d.max()

98

In [66]:
coba1d.min()

3

In [69]:
coba2d

array([[28,  1, 28, 98, 98],
       [17, 68, 84, 36, 31],
       [41, 49, 21, 17, 32],
       [97, 25, 25, 35, 16]])

In [70]:
coba1d.argmax()

1

In [71]:
coba2d.argmax()

3

In [72]:
coba1d.argmin()

3

In [74]:
coba2d.argmin()

1

In [77]:
coba1d.shape

(20,)

In [78]:
coba2d.shape

(4, 5)

In [79]:
coba1d.dtype

dtype('int32')

In [80]:
coba2d.dtype

dtype('int32')

In [81]:
# Indexing di Numpy


In [82]:
coba = np.arange(0, 11)


In [84]:
coba

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [85]:
coba[6]

6

In [86]:
coba[5:]

array([ 5,  6,  7,  8,  9, 10])

In [87]:
coba[5:9]

array([5, 6, 7, 8])

In [92]:
coba2 = coba[:6]  #mengambil sebagian array

In [93]:
coba2

array([0, 1, 2, 3, 4, 5])

In [94]:
coba2[:] = 100  #tidak di rekomendasikan mencopy semua data

In [95]:
coba2

array([100, 100, 100, 100, 100, 100])

In [96]:
coba

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [99]:
coba4 = coba.copy()

In [100]:
coba4[:] = 100

In [101]:
coba4

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [102]:
coba

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [103]:
bil2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [104]:
bil2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [105]:
bil2d[0][0]  #tidak di rekomendasikan

1

In [106]:
bil2d[2][2]  #tidak di rekomendasikan

9

In [116]:
bil2d[1:2, 0:1]

array([[4]])

In [117]:
# Slicing dengan boolean di Numpy

TypeError: arange() requires stop to be specified.

In [134]:
bil = np.arange(1, 11)

In [135]:
bil

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
angkaT = bil > 5

In [128]:
angkaT

array([ True,  True,  True,  True,  True])

In [129]:
bil = bil[angkaT]

In [131]:
bil

array([ 6,  7,  8,  9, 10])

In [137]:
bil[bil>4]

array([ 5,  6,  7,  8,  9, 10])